apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: problem-1
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      readOnlyRootFilesystem: true
    resources:
      limits: 
         memory: 1Mi
         cpu: 0.1m
      
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
